### ISSUE TITLE
hclust2 installation

### ISSUE THREAD

**Issue by vsblancato** [biobakery/homebrew-biobakery#11]
I tried to install hclust2 with: brew install hclust2.
But i get an error:
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib/libquadmath.so.0)
with: brew install glibc
i get: Warning: glibc 2.23 is already installed
First GLIBC_2.23 is not found and then is already installed.
Any suggestions?
Thanks

**Comment by ljmciver** [comment]
Hello - Do you have $LD_LIBRARY_PATH set? If so, this can break dynamic linking with brew. If this is the case unset this variable and remove the gcc/glibc installs and reinstall. If this is not the case it might help to force the install of these packages from source (instead of bottles). Setting this variable should always install from source: $ export HOMEBREW_BUILD_FROM_SOURCE=1 . Please comment and/or reopen this ticket if you have any questions and/or issues.

Thanks,
Lauren
