### ISSUE TITLE
error: library dfftpack has Fortran sources but no Fortran compiler found

### ISSUE THREAD

**Issue by natachacouto** [biobakery/homebrew-biobakery#22]
Hi. I am trying to install metaphlan2, but I get this issue:

Last 15 lines from /Users/natachacouto/Library/Logs/Homebrew/metaphlan2/04.python2:
customize IBMFCompiler
Could not locate executable xlf90
Could not locate executable xlf
customize IntelFCompiler
Could not locate executable ifort
Could not locate executable ifc
customize GnuFCompiler
Could not locate executable g77
customize G95FCompiler
Could not locate executable g95
customize PGroupFCompiler
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
building 'dfftpack' library
error: library dfftpack has Fortran sources but no Fortran compiler found

I have tried reinstalling gcc, linking it, but I can't get it working.
Can you help me?

**Comment by ljmciver** [comment]
Hi - It looks like you are having issues installing scipy (one of MetaPhlAn2's dependencies) from source. My suggestion would be to install MetaPhlAn2 without the numpy/scipy dependencies by adding the option "--without-dependencies". And then install numpy/scipy individually with "brew install scipy" because with this method you might be able to use a bottle pre-compiled for your OS. I believe this should resolve the error you are seeing. Please reopen the issue if you continue to have errors.

Thanks,
Lauren
