### ISSUE TITLE
Problem installing Maaslin

### ISSUE THREAD

**Issue by SamanthaNicole** [biobakery/homebrew-biobakery#28]
Hello I'm trying to use Homebrew to install maaslin and the installation is having a problem that I'm not able to identify.  

I am running MAC High Sierra v. 10.13.6.

This is the command I used to install: 
`brew install biobakery/biobakery/maaslin`

This is the output from running the above command:
```
==> Installing maaslin from biobakery/biobakery
==> Downloading https://bitbucket.org/biobakery/maaslin/downloads/Maaslin_0.0.5.tar.gz
Already downloaded: /Users/kirbylab/Library/Caches/Homebrew/maaslin-0.0.5.tar.gz
==> Downloading https://pypi.python.org/packages/source/b/blist/blist-1.3.6.tar.gz
Already downloaded: /Users/kirbylab/Library/Caches/Homebrew/maaslin--blist-1.3.6.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/maaslin/0.0.5/libexec/vendor --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/kirbylab/Library/Logs/Homebrew/maaslin/01.python2:
2018-07-24 15:11:12 -0500

python2
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/maaslin/0.0.5/libexec/vendor
--single-version-externally-managed
--record=installed.txt


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues
```

Thank you,
Samantha

**Comment by ljmciver** [comment]
Hi Samantha - It looks like it is having an issue installing the maaslin dependency blist. It is a python package that is required for one of the maaslin utility scripts. I would suggest installing maaslin with the new option "--without-python-packages". This will skip the blist install. If you need blist (because you are running the maaslin utility scripts) try installing it with pip or another package manager. Please respond to this ticket if you continue to have issues (or have any additional questions).

Thanks,
Lauren
