### ISSUE TITLE
Error message with HUMAnN2

### ISSUE THREAD

**Issue by olsonca** [biobakery/homebrew-biobakery#38]
Hello,

After installing HUMAnN2, I get the following error message trying to run the first command (inputting sample files):

"CRITICAL ERROR: The metaphlan2.py executable can not be found. Please check the install."

I have installed metaphlan2 and python, and I am not sure how to troubleshoot this- can you please help me understand what could be causing this issue? Thank you.

Best,
Christine

**Comment by ljmciver** [comment]
Hello - My guess is humann2 is unable to read the version info for metaphlan2 likely because additional information is printed. If you run "$ metaphlan2.py --version" look for additional text other than the version info. If you resolve this text it should resolve the humann2 error you are seeing. Please post if you have other issues.

Thanks!
Lauren

**Comment by olsonca** [comment]
Hello Lauren,

Sorry, I tried to check the version and my error message read that I needed to install Python2. However, in the current directory, if I run "python --version", I see that Python 2.7.6 is installed. Sorry for bugging you, but I think that metaphlan2 may not be properly configured. Thanks for your help!

**Comment by ljmciver** [comment]
Hello, Sorry you are having issues installing humann2 and metaphlan2 with homebrew. Would you possibly want to try installing with Conda instead of homebrew? See the wiki for the instructions: https://bitbucket.org/biobakery/biobakery/wiki/biobakery_wiki . If you have any issues with conda please post to the biobakery conda recipe repo. We are moving away from homebrew and now supporting conda and docker. 

Thanks!
Lauren
